// Code generated by github.com/spacemeshos/borsh/gen. DO NOT EDIT.

package main

import (
	"io"

	"github.com/spacemeshos/borsh"
)

func (t *Hello) MarshalBorsh(w io.Writer) error {
	if err := borsh.WriteBytes(w, t.ID[:]); err != nil {
		return err
	}
	return nil
}
